on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:   
        # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - name: Checkout action step
        uses: actions/checkout@v2
      
      # Generate JarvisGif
      - name: Generate Jarvis Gif action step
        id: hello
        uses: BILLKATO/JRVS@main
        with:
          who-to-greet: 'Gabriel Mitsuo Kaiya'
      
      # Use the output time from the previous step
      - name: Get the output time action step
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      
      # listing files
      - name: Get files 1 time action step
        run: dir
        
      # listing files
      - name: Get files 2 time action step
        run: ls    
      
      # Para as atualizações.
      - name: Push changes action step
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
