on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:   
        # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Hello world action step
        id: hello
        uses: BILLKATO/JRVS@main
        with:
          who-to-greet: 'Gabriel Mitsuo Kaiya'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      
      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
